name: "Build FAP"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flipper App Package
        uses: flipperdevices/flipperzero-ufbt-action@v1
        with:
          sdk-channel: dev # Set to 'release' or change channel based on Momentum compatibility
